### ISSUE TITLE
Facing issue after adding this package in my application

### ISSUE THREAD

**Issue by Tusshark** [peterfournier/MagTek#1]
Hi,
    I am facing issue with this package after adding in my application. I am getting errors like Below:
/Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (PaymentServiceNetwork.iOS)

/Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/error MT5209: Error: warning: ignoring file /Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone8.1-9.3/mtouch-cache/libMTSCRA.a, missing required architecture x86_64 in file /Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone8.1-9.3/mtouch-cache/libMTSCRA.a (3 slices) (PaymentServiceNetwork.iOS) Native linking

/Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: MTCardData. The symbol '_OBJC_CLASS_$_MTCardData' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (PaymentServiceNetwork.iOS)

/Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: MTSCRA. The symbol '_OBJC_CLASS_$_MTSCRA' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (PaymentServiceNetwork.iOS)

/Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone8.1-9.3/Entitlements.xcent (MT5201) (PaymentServiceNetwork.iOS)

/Users/chetu/Desktop/Tusshar/CurrentApp/PsnAmcApp/App12/App12.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (PaymentServiceNetwork.iOS)

So, Please help me with this issue. I am facing this same issue from long time.

**Comment by peterfournier** [comment]
Hey sorry, this package will not work with simulators :(

MagTek provides a different library that's required for simulators, and I don't have a package for it. In my own opinion, it's better to test on device only. You can't the iDynamo device, and I believe you can't test the eDynamo either.

**Comment by Tusshark** [comment]
Okay,
        Now, I have all things required for this, but currently I am facing an issue , for when I am going to call the magtek my application crash and given me an exception.

**Comment by peterfournier** [comment]
Are you getting a different exception than the one above? If so, can you copy it here
