### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by PankajKumarRajput** [peterfournier/MagTek#2]
@peterfournier Can you please provide a sample to use it in xamarin forms

**Comment by peterfournier** [comment]
Hi,

Yes I can get a same project up. Give me about a week, 

Thanks!

**Comment by PankajKumarRajput** [comment]
@peterfournier Any update on this

**Comment by peterfournier** [comment]
Hi, I've created the project, working on getting it building. It was part of a larger project, so I'm pulling it out and giving you only what you need. Works been busy, but I'll should be up soon.

thanks

**Comment by PankajKumarRajput** [comment]
@peterfournier 
Still waiting for update

**Comment by peterfournier** [comment]
I have most of the sample project done. I'll be condensing it into it's own
nuget soon with some simple API's. As of know, you'll need to do some copy
and pasting ninja stuff. I'll try to post it by the end of the day.

**Comment by peterfournier** [comment]
Sample project is up. Not fully tested with iOS.

Hope that helps!
